app <- ShinyDriver$new("../../")
# change path for interactice use
# app <- ShinyDriver$new("../../")

# I hard coded the file locations into the app in test mode because shinyFiles
# seemed to not work with the testing

app$snapshotInit("basic_demo_run")

app$setInputs(start = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(assessor_name = "Sarah", wait_ = FALSE, values_ = FALSE)
app$setInputs(geo_location = "Canada", wait_ = FALSE, values_ = FALSE)
app$setInputs(tax_grp = "Bird", wait_ = FALSE, values_ = FALSE)
app$setInputs(species_name = "Bubo ", wait_ = FALSE, values_ = FALSE)
app$setInputs(common_name = "Snowy Owl", wait_ = FALSE, values_ = FALSE)
app$setInputs(mig = TRUE, wait_ = FALSE, values_ = FALSE)
app$setInputs(next1 = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(clim_var_dir = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(range_poly_pth = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(assess_poly_pth = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(nonbreed_poly_pth = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(hs_rast_pth = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(loadSpatial = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(next2 = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(B1 = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(B2a = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(B2b = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(comB3 = "A comment for B3", wait_ = FALSE, values_ = FALSE)
app$setInputs(B3 = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(C1 = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(C2bii = "2", wait_ = FALSE, values_ = FALSE)
app$setInputs(C2c = "0", wait_ = FALSE, values_ = FALSE)
app$setInputs(C2d = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(C3 = "0", wait_ = FALSE, values_ = FALSE)
app$setInputs(C4a = "0", wait_ = FALSE, values_ = FALSE)
app$setInputs(C4b = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(C4d = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(C4e = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(C4f = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(C4g = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(C5a = "0", wait_ = FALSE, values_ = FALSE)
app$setInputs(C6 = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(D1 = "2", wait_ = FALSE, values_ = FALSE)
app$setInputs(D4 = "1", wait_ = FALSE, values_ = FALSE)
app$setInputs(nextVuln = "click", wait_ = FALSE, values_ = FALSE)
app$setInputs(submitSpatVuln = "click", wait_ = FALSE, values_ = FALSE)
app$waitForValue("index", iotype = "output")
app$snapshot(list(output = TRUE))
