app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(prep_data = "click")
app$setInputs(`data_prep_mod-allow_over` = TRUE)
app$setInputs(`data_prep_mod-submit` = "click")
app$waitForValue("data_prep_msg", iotype = "output", timeout = 30000)
app$setInputs(data_done = "click")
app$setInputs(start = "click")
app$setInputs(assessor_name = "Sarah")
app$setInputs(geo_location = "Canad")
app$setInputs(tax_grp = "Bird")
app$setInputs(species_name = "bir")
app$setInputs(species_name = "birb")
app$setInputs(species_name = "birbi")
app$setInputs(next1 = "click")
app$setInputs(loadSpatial = "click")
app$setInputs(next2 = "click")
app$setInputs(B1 = "0")
app$setInputs(B2a = "1")
app$setInputs(B2b = "0")
app$setInputs(B3 = "0")
app$setInputs(B3 = c("2", "0"))
app$setInputs(C1 = "3")
app$setInputs(C1 = c("3", "0"))
app$setInputs(C2bii = "0")
app$setInputs(C2c = "0")
app$setInputs(C2d = "1")
app$setInputs(C3 = "1")
app$setInputs(C4a = "0")
app$setInputs(C4b = "0")
app$setInputs(C4d = "0")
app$setInputs(C4e = "0")
app$setInputs(C4f = "0")
app$setInputs(C4g = "0")
app$setInputs(C5a = "0")
app$setInputs(D1 = "0")
app$setInputs(D1 = c("3", "0"))
app$setInputs(next3 = "click")
app$setInputs(next4 = "click")
app$setInputs(calcIndex = "click")
app$waitForValue("index", iotype = "output", timeout = 30000)
app$snapshot(list(output = TRUE))
