app <- ShinyDriver$new("../../", loadTimeout = 1e+05, seed = 123)
app$snapshotInit("mytest")

app$setInputs(prep_data = "click", wait_=FALSE, values_=FALSE)
app$setInputs(`data_prep_mod-allow_over` = TRUE, wait_=FALSE, values_=FALSE)
app$setInputs(`data_prep_mod-submit` = "click", wait_=FALSE, values_=FALSE)
app$waitForValue("data_prep_msg", iotype = "output", timeout = 30000)
app$setInputs(data_done = "click", wait_=FALSE, values_=FALSE)
app$setInputs(start = "click", wait_=FALSE, values_=FALSE)
app$setInputs(assessor_name = "Sarah", wait_=FALSE, values_=FALSE)
app$setInputs(geo_location = "Canad", wait_=FALSE, values_=FALSE)
app$setInputs(tax_grp = "Bird", wait_=FALSE, values_=FALSE)
app$setInputs(species_name = "birbi", wait_=FALSE, values_=FALSE)
app$setInputs(next1 = "click", wait_=FALSE, values_=FALSE)
app$setInputs(loadSpatial = "click", wait_=FALSE, values_=FALSE)
app$setInputs(next2 = "click", wait_=FALSE, values_=FALSE)
app$setInputs(B1 = "0", wait_=FALSE, values_=FALSE)
app$setInputs(B2a = "1", wait_=FALSE, values_=FALSE)
app$setInputs(B2b = "0", wait_=FALSE, values_=FALSE)
app$setInputs(B3 = "0", wait_=FALSE, values_=FALSE)
app$setInputs(B3 = c("2", "0"), wait_=FALSE, values_=FALSE)
app$setInputs(C1 = "3", wait_=FALSE, values_=FALSE)
app$setInputs(C1 = c("3", "0"), wait_=FALSE, values_=FALSE)
app$setInputs(C2bii = "0", wait_=FALSE, values_=FALSE)
app$setInputs(C2c = "0", wait_=FALSE, values_=FALSE)
app$setInputs(C2d = "1", wait_=FALSE, values_=FALSE)
app$setInputs(C3 = "1", wait_=FALSE, values_=FALSE)
app$setInputs(C4a = "0", wait_=FALSE, values_=FALSE)
app$setInputs(C4b = "0", wait_=FALSE, values_=FALSE)
app$setInputs(C4d = "0", wait_=FALSE, values_=FALSE)
app$setInputs(C4e = "0", wait_=FALSE, values_=FALSE)
app$setInputs(C4f = "0", wait_=FALSE, values_=FALSE)
app$setInputs(C4g = "0", wait_=FALSE, values_=FALSE)
app$setInputs(C5a = "0", wait_=FALSE, values_=FALSE)
app$setInputs(D1 = "0", wait_=FALSE, values_=FALSE)
app$setInputs(D1 = c("3", "0"), wait_=FALSE, values_=FALSE)
app$setInputs(next3 = "click", wait_=FALSE, values_=FALSE)
app$setInputs(next4 = "click", wait_=FALSE, values_=FALSE)
app$setInputs(calcIndex = "click", wait_=FALSE, values_=FALSE)
app$waitForValue("index", iotype = "output", timeout = 30000)
app$snapshot(list(output = TRUE))
